[program:laravel-queue-default]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/colife_db/artisan queue:work --queue=default --sleep=1 --tries=3 --backoff=5 --timeout=120 --memory=256
directory=/var/www/colife_db
environment=CACHE_STORE="file",DB_CONNECTION="mysql",QUEUE_CONNECTION="database",APP_ENV="production"
autostart=true
autorestart=true
startsecs=3
stopasgroup=true
killasgroup=true
user=root
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/colife_db/storage/logs/queue-default-worker.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=5
stopwaitsecs=3600

[program:laravel-queue-pauses]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/colife_db/artisan queue:work --queue=bp-pauses --sleep=1 --tries=5 --backoff=5 --timeout=120 --memory=256
directory=/var/www/colife_db
environment=CACHE_STORE="file",DB_CONNECTION="mysql",QUEUE_CONNECTION="database",APP_ENV="production"
autostart=true
autorestart=true
startsecs=3
stopasgroup=true
killasgroup=true
user=root
numprocs=2
redirect_stderr=true
stdout_logfile=/var/www/colife_db/storage/logs/queue-bp-pauses-worker.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=5
stopwaitsecs=3600
